In [1]:
# Layers

import torch
import torch.nn as nn

model=nn.Sequential(
    nn.Linear(2,4),      # 2 input ko numbers/layers  4 me convert krna hidden layers
    nn.ReLU(),           # -sign ko plus me krna learning achi huti ha 
    nn.Linear(4,1),      #  4 layers ko 1 me krna [2,1,3,4]  [10]
    nn.Sigmoid()         #  0 & 1 ka darmiyan value lana 
)
x=torch.tensor([[5.0,6.0]])
output=model(x)
print(output)

tensor([[0.8379]], grad_fn=<SigmoidBackward0>)


In [2]:
# weights & Bias

import torch
import torch.nn as nn
layer=nn.Linear(2,1)

print("weight",layer.weight)
print("bias",layer.bias)

x=torch.tensor([[5.0,6.0]])
output=layer(x)
print("output",output)

weight Parameter containing:
tensor([[-0.2587, -0.2542]], requires_grad=True)
bias Parameter containing:
tensor([0.4154], requires_grad=True)
output tensor([[-2.4031]], grad_fn=<AddmmBackward0>)


In [3]:
# Activation Functions

import torch 
import torch.nn as nn

x=torch.tensor([[-0.3,5,-6,3]])
y=torch.tensor([[2.5]])
z=torch.tensor([[3.0,6.0,8.0]])

ReLU=nn.ReLU()
Sigmoid=nn.Sigmoid()
Tanh=nn.Tanh()

print("ReLU",ReLU(x))
print("Sigmoid",Sigmoid(y))
print("Tanh",Tanh(z))

ReLU tensor([[0., 5., 0., 3.]])
Sigmoid tensor([[0.9241]])
Tanh tensor([[0.9951, 1.0000, 1.0000]])


In [4]:
# Loss Function

import torch
import torch.nn as nn

y_true=torch.tensor([[1.0]])
y_pred=torch.tensor([[0.7]],requires_grad=True)

loss=nn.BCELoss()
output=loss(y_pred, y_true)
print("Loss", output.item())

Loss 0.3566749691963196


In [5]:
# Back Propogation

import torch
import torch.nn as nn
import torch.optim as optim

x=torch.tensor([[5.0,6.0]])
y_true=torch.tensor([[1.0]])

# Model

model=nn.Sequential(
    nn.Linear(2,4),
    nn.ReLU(),
    nn.Linear(4,1),
    nn.Sigmoid()
)

# Optimizer

optimizer=optim.SGD(model.parameters(),lr=0.01)

# loss

loss_fn=nn.BCELoss()

# Forward 

y_pred=model(x)
loss=loss_fn(y_pred,y_true)
print("loss",loss.item())

# Backpropogation

optimizer.zero_grad()
loss.backward()
optimizer.step()

y_pred2=model(x)
output_2=loss_fn(y_pred,y_true)
print("final",output_2.item())



loss 1.4217662811279297
final 1.4217662811279297
